image:
    # на этом VM-образе установлены все Visual Studio с 2008 по 2015
    - Visual Studio 2015
    - Ubuntu

init:
    # секция инициализации, исполняется до клонирования проекта
    # скорее всего, строчка ниже необязательна (так должно быть по умолчанию),
    # вместе с тем, она присутствует в официальных примерах, так что пусть будет:
    - git config --global core.autocrlf input

#clone_folder: c:\projects\my-prj # выбираем локальную директорию для клонирования
shallow_clone: true              # копируем только последний коммит, без истории (git clone --depth 1)

matrix:
    fast_finish: false           # не останавливаемся после возникновения ошибки в каком-то из заданий

platform:
    - x86

install:
    - cmd: call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86
    - sh: sudo apt-get install -y ninja-build

build_script:
    - cmd: cd src
    - cmd: cmake -H. -Bbuild
    - cmd: cmake --build build --config Release
    - cmd: cd ..
    - cmd: cd test
    - cmd: cmake -H. -Bbuild
    - cmd: cmake --build build --config Release
    - cmd: cd ..
    - sh: cd src
    - sh: cmake -H. -Bbuild -DCMAKE_BUILD_TYPE=Release -G Ninja
    - sh: cmake --build build
    - sh: cd ..
    - sh: cd test
    - sh: cmake -H. -Bbuild -DCMAKE_BUILD_TYPE=Release -G Ninja
    - sh: cmake --build build
    - sh: cd ..

test_script:
    - cmd: test\build\Release\testlab10.exe src\build\Release\lab10.exe
    - sh: chmod +x test\build\Release\testlab10
    - sh: chmod +x src\build\Release\lab10
    - sh: test\build\Release\testlab10 src\build\Release\lab10