version: 1.0.{build}
image:
- Visual Studio 2019
- Ubuntu2004
build_script:
- ps: cmake -Bbuild
- ps: cd build
- ps: cmake --build . --target lab_test lab_src
test_script:
- ps: ctest -C Debug --rerun-failed --output-on-failure 2> $null
- ps: if (Test-Path ./Testing/Temporary/LastTestsFailed.log) { exit 1 }
notifications:
- provider: Email
  to:
  - '{{commitAuthorEmail}}'
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true