version: 1.0.{build}
image:
- Visual Studio 2019
- Ubuntu2004
build_script:
- ps: cmake -B build_test
- ps: cmake --build build_test --target lab_test lab_src
test_script:
- ps: if ($IsWindows) {cmake --build build_test --target RUN_TESTS}
- ps: if ($IsLinux) {cmake --build build_test --target test}
after_test:
- ps: if ($IsWindows) {$ARTIFACTS = build_test_Windows}
- ps: if ($IsLinux) {$ARTIFACTS = build_test_Linux}
- ps: 7z a "$ARTIFACTS.zip" $ARTIFACTS
- ps: Push-AppveyorArtifact "$ARTIFACTS.zip"
- ps: if (Test-Path ./Testing/Temporary/LastTestsFailed.log) { exit 1 }
artifacts:
- path: build_test_Windows.zip
  name: build_test_Windows
- path: build_test_Linux.zip
  name: build_test_Linux
notifications:
- provider: Email
  to:
  - '{{commitAuthorEmail}}'
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true