version: 1.0.{build}
image:
- Visual Studio 2019
- Ubuntu2004
build_script:
- pwsh: cmake -Bbuild
- pwsh: cd build
- pwsh: cmake --build . --target lab_test lab_src
test_script:
- pwsh: ctest -C Debug --rerun-failed --output-on-failure
- pwsh: if (Test-Path ./Testing/Temporary/LastTestsFailed.log) { exit 1 }
notifications:
- provider: Email
  to:
  - '{{commitAuthorEmail}}'
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true